version: '2'
services:
    redis-ruby:
        image: ruby:2.4-alpine3.6
        depends_on:
          - db
        volumes:
          - source_data:/root
    db:
        image: redis:4-alpine
        ports:
            - "6379:6379"
        volumes:
          - redis_data:/data
volumes:
  redis_data:
  source_data:
    - .:
